# Generated by Django 3.2.8 on 2021-10-30 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=124)),
                ('city', models.CharField(max_length=124)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('destination', models.ForeignKey(max_length=124, on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='rides.station')),
                ('origin', models.ForeignKey(max_length=124, on_delete=django.db.models.deletion.CASCADE, related_name='dapartures', to='rides.station')),
            ],
        ),
    ]
