# Generated by Django 3.2.8 on 2021-11-21 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_customer_order_orderticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderticket',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rides.order'),
        ),
    ]
