# Generated by Django 3.2.8 on 2021-11-22 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_orderticket_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderticket',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderticket',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.customer'),
        ),
    ]
