# Generated by Django 3.2.8 on 2021-11-22 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_auto_20211122_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ride',
        ),
    ]
